n1=float(input())
n2=float(input())
s=n1+n2
ss=n1-n2
m=n1*n2
d=n1/n2
dd=n1//n2
dp=n1%n2
c=n1**n2
print(f"{s:.0f}")
print(f"{ss:.0f}")
print(f"{m:.0f}")
print(f"{d}")
print(f"{dd:.0f}")
print(f"{dp:.0f}")
print(f"{c:.0f}")